<?php
/**
 * Created by PhpStorm.
 * User: night
 * Date: 2021/5/11
 * Time: 16:39
 */

namespace App\Services\Logic\SqlUpdate;


class Sql
{

    public static $sqlTable = [

        /************************公共部分表**************************/
            'CREATE TABLE IF NOT EXISTS `comm_conf` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'配置名称\',
              `key` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'识别KEY\',
              `type` tinyint(4) DEFAULT \'1\' COMMENT \' 数据类型 1.广告招商 2. 下载本站 3.关于我们 4.友情链接 5.隐私条款  \',
              `sort` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'排序值\',
              `values` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 配置的值根据数据类型解析\',
              `rich_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 配置的值根据数据类型解析\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_comm_conf_id` (`id`) USING BTREE,
              KEY `id_comm_conf_key` (`key`) USING BTREE,
              KEY `id_comm_conf_name` (`name`) USING BTREE,
              KEY `id_comm_conf_type` (`type`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'公共配置表\';',//公共配置表

            'CREATE TABLE IF NOT EXISTS `complaints` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `avid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'\' COMMENT \'番号\',
              `topic` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT \'主题\',
              `title` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT \'标题\',
              `content` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'\' COMMENT \'内容\',
              `device` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'\' COMMENT \'登录设备\',
              `connect` varchar(255) CHARACTER SET utf8mb4 NOT NULL DEFAULT \'\' COMMENT \'联系方式\',
              `remark` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT \'\' COMMENT \'备注\',
              `created_at` timestamp NULL DEFAULT NULL,
              `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
              PRIMARY KEY (`id`),
              KEY `id_complaints_avid` (`avid`) USING BTREE
            ) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'意见反馈表\';',

            'CREATE TABLE IF NOT EXISTS `system_announcements` (
              `id` int unsigned NOT NULL AUTO_INCREMENT,
              `uuid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT \'uuid\',
              `type` tinyint unsigned DEFAULT \'1\' COMMENT \'类型 1.top  2.content 3.message\',
              `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'标题\',
              `content` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'内容\',
              `url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'链接\',
              `display_type` tinyint unsigned DEFAULT \'1\' COMMENT \'显示方式 1. \',
              `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
              `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
              PRIMARY KEY (`id`),
              UNIQUE KEY `uuid_uqi` (`uuid`)
            ) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'公告表\';',

            'CREATE TABLE IF NOT EXISTS `reports` (
              `id` int unsigned NOT NULL AUTO_INCREMENT,
              `uuid` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT \'uuid\',
              `u_number` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT \'主题\',
              `uid` int unsigned NOT NULL,
              `avid` varchar(128) CHARACTER SET utf8mb4 DEFAULT \'\' COMMENT \'番号\',
              `reason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'举报原因\',
              `content` text COLLATE utf8mb4_unicode_ci COMMENT \'内容\',
              `remark` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'备注\',
              `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
              `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
              PRIMARY KEY (`id`),
              KEY `reports_uid_index` (`uid`),
              KEY `reports_avid_index` (`avid`)
            ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT=\'举报表\';',


        /************************用户部分表**************************/
            'CREATE TABLE IF NOT EXISTS `user_client` (
              `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
              `number` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户识别码-本平台\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'账号状态状态 1.正常  2.禁用/黑名单  \',
              `phone` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户手机号\',
              `email` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户邮箱\',
              `nickname` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户昵称\',
              `pwd` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户密码\',
              `sex` tinyint(4) DEFAULT \'0\' COMMENT \'用户性别 0未知 1男 2女\',
              `type` tinyint(4) DEFAULT \'1\' COMMENT \'用户类型 1普通用户 2运营账户 3 VIP会员【这个后面可能需要调整】\',
              `age` int(11) unsigned DEFAULT NULL COMMENT \'用户年龄\',
              `attention` int(11) unsigned DEFAULT NULL COMMENT \'用户关注数量-冗余\',
              `fans` int(11) unsigned DEFAULT NULL COMMENT \'用户粉丝数量-冗余\',
              `piece_list_num` int(11) unsigned DEFAULT NULL COMMENT \'用户片单数量-冗余\',
              `seen_num` int(11) unsigned DEFAULT NULL COMMENT \'用户看过数量-冗余\',
              `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'头像\',
              `intro` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户简介\',
              `le_phone_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'手机认证时间\',
              `le_phone_status` tinyint(4) DEFAULT \'2\' COMMENT \'手机认证状态 1.认证  2.未认证 \',
              `le_email_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'邮箱认证时间\',
              `le_email_status` tinyint(4) DEFAULT \'2\' COMMENT \'邮箱认证状态 1.认证  2.未认证 \',
              `login_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'用户最近登录时间\',
              `login_ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'用户最近登录ip\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              UNIQUE KEY `number` (`number`),
              KEY `id_user_id` (`id`) USING BTREE,
              KEY `id_user_number` (`number`) USING BTREE,
              KEY `id_user_phone` (`phone`) USING BTREE,
              KEY `id_user_email` (`email`) USING BTREE,
              KEY `id_user_nickname` (`nickname`) USING BTREE,
              KEY `id_user_type` (`type`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户基础信息表\';',

            'CREATE TABLE IF NOT EXISTS `user_browse_movie` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  3.有新的记录\',
              `browse_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'浏览时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_browse_movie_id` (`id`) USING BTREE,
              KEY `id_user_browse_movie_uid` (`uid`) USING BTREE,
              KEY `id_user_browse_movie_mid` (`mid`) USING BTREE,
              KEY `id_user_browse_movie_browse_time` (`browse_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户浏览影片记录表\';',

            'CREATE TABLE IF NOT EXISTS `user_want_see_movie` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
              `mark_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'标记时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_want_see_movie_id` (`id`) USING BTREE,
              KEY `id_user_want_see_movie_uid` (`uid`) USING BTREE,
              KEY `id_user_want_see_movie_mid` (`mid`) USING BTREE,
              KEY `id_user_want_see_movie_mark_time` (`mark_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户想看影片表\';',

            'CREATE TABLE IF NOT EXISTS `user_seen_movie` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
              `score` float NOT NULL DEFAULT \'0\' COMMENT \'评分\',
              `mark_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'标记时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_seen_movie_id` (`id`) USING BTREE,
              KEY `id_user_seen_movie_uid` (`uid`) USING BTREE,
              KEY `id_user_seen_movie_mid` (`mid`) USING BTREE,
              KEY `id_user_seen_movie_mark_time` (`mark_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户看过影片表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_actor` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'收藏时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_actor_id` (`id`) USING BTREE,
              KEY `id_user_like_actor_uid` (`uid`) USING BTREE,
              KEY `id_user_like_actor_aid` (`aid`) USING BTREE,
              KEY `id_user_like_actor_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户收藏演员表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_director` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `did` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'导演ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'收藏时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_director_id` (`id`) USING BTREE,
              KEY `id_user_like_director_uid` (`uid`) USING BTREE,
              KEY `id_user_like_director_did` (`did`) USING BTREE,
              KEY `id_user_like_director_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户收藏导演表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_series` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `series_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'系列ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'收藏时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_series_id` (`id`) USING BTREE,
              KEY `id_user_like_series_uid` (`uid`) USING BTREE,
              KEY `id_user_like_series_series_id` (`series_id`) USING BTREE,
              KEY `id_user_like_series_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户收藏系列表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_film_companies` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `film_companies_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'片商ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'收藏时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_film_companies_id` (`id`) USING BTREE,
              KEY `id_user_like_film_companies_uid` (`uid`) USING BTREE,
              KEY `id_user_like_film_companies_film_companies_id` (film_companies_id) USING BTREE,
              KEY `id_user_like_film_companies_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户收藏片商表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_number` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `nid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'番号ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.删除  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'收藏时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_number_id` (`id`) USING BTREE,
              KEY `id_user_like_number_uid` (`uid`) USING BTREE,
              KEY `id_user_like_number_nid` (`nid`) USING BTREE,
              KEY `id_user_like_number_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户收藏番号表\';',

            'CREATE TABLE IF NOT EXISTS `user_like_user` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `goal_uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'目标用户ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \'账号状态状态 1.关注  2.取消关注  \',
              `like_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关注时间\',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_like_user_id` (`id`) USING BTREE,
              KEY `id_user_like_user_uid` (`uid`) USING BTREE,
              KEY `id_user_like_user_goal_uid` (`goal_uid`) USING BTREE,
              KEY `id_user_like_user_goal_like_time` (`like_time`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户关注用户表\';',

            'CREATE TABLE IF NOT EXISTS `user_piece_list` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
              `plid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'片单ID\',
              `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
              `type` tinyint(4) DEFAULT \'1\' COMMENT \'1.默认 2.创建  3.收藏  \',
              `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
              `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
              PRIMARY KEY (`id`),
              KEY `id_user_piece_list_id` (`id`) USING BTREE,
              KEY `id_user_piece_list_uid` (`uid`) USING BTREE,
              KEY `id_user_piece_list_pid` (`plid`) USING BTREE,
              KEY `id_user_piece_list_created_at` (`created_at`) USING BTREE
            ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户片单表\';',


            'CREATE TABLE IF NOT EXISTS `user_client_event` (
                `id` BIGINT (20) NOT NULL AUTO_INCREMENT,
                `uid` INT (10) UNSIGNED NOT NULL COMMENT \'用户主键id\',
                `reply` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'收到用户回复数\',
                `like` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'收到点赞数\',
                `my_comment` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'我的评论\',
                `my_reply` INT (111) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'我的回复\',
                `my_like` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'我的点赞\',
                `dislike` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'踩\',
                `report` INT (11) UNSIGNED NOT NULL DEFAULT \'0\' COMMENT \'举报数\',
                `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
                `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
                PRIMARY KEY (`id`),
                UNIQUE KEY `id_user_client_event_uid` (`uid`) USING BTREE
            ) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMENT = \'用户事件表\';',

            'CREATE TABLE IF NOT EXISTS `notify` (
                `id` BIGINT (20) NOT NULL AUTO_INCREMENT,
                `content` text COMMENT \'消息内容\',
                `target_id` INT (11) DEFAULT \'0\' COMMENT \'目标的ID\',
                `target_source_id` INT (10) UNSIGNED DEFAULT \'0\' COMMENT \'目标父级id 针对回复和评论\',
                `target_type` VARCHAR (20) DEFAULT \'\' COMMENT \'目标的类型\',
                `type` TINYINT (1) DEFAULT \'0\' COMMENT \'1.赞2.踩3.我的评论4.回复我的5.关注99.公告内容\',
                `sender_id` BIGINT (20) DEFAULT \'0\' COMMENT \'发送者ID 0:管理员\',
                `sender_name` VARCHAR (60) DEFAULT \'\' COMMENT \'发送者名称(真实nickname,管理员admin)\',
                `sender_avatar` VARCHAR (255) DEFAULT \'\' COMMENT \'发送者的头像路径\',
                `is_read` SMALLINT (1) NOT NULL DEFAULT \'0\' COMMENT \'0:未读 1.已读\',
                `uid` BIGINT (20) DEFAULT \'0\' COMMENT \'消息的所属者\',
                `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
                `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (`id`),
                KEY `id_message_notify_target_id` (`target_id`),
                KEY `id_message_notify_sender_id` (`sender_id`),
                KEY `id_message_notify_user_id` (`uid`)
            ) ENGINE = INNODB DEFAULT CHARSET = utf8mb4 COMMENT = \'用户消息通知表\';',

        /************************采集部分表**************************/
        'CREATE TABLE IF NOT EXISTS `collection_original` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `oid` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'mongoDb id\',
          `number` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号\',
          `db_name` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'所属mongodb表\',
          `dis_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理计数 为防止意外一个影片数据会处理两次\',
          `data` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数据\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理 3.需要重新处理  \',
          `ctime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'采集方的创建时间 最大值用于从采集那边的筛选条件\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_original_id` (`id`) USING BTREE,
          KEY `id_collection_original_oid` (`oid`) USING BTREE,
          KEY `id_collection_original_number` (`number`) USING BTREE,
          KEY `id_collection_original_dis_sum` (`dis_sum`) USING BTREE,
          KEY `id_collection_original_ctime` (`ctime`) USING BTREE,
          KEY `id_collection_original_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集原始数据表\';',

        'CREATE TABLE IF NOT EXISTS `collection_film_companies` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'片商名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `category` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 类别\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理 5.异常数据需要人工处理\',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_film_companies_id` (`id`) USING BTREE,
          KEY `id_collection_film_companies_name` (`name`) USING BTREE,
          KEY `id_collection_film_companies_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_film_companies_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集片商表\';',

        'CREATE TABLE IF NOT EXISTS `collection_actor` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员名称-主\',
          `photo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员照片\',
          `sex` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员性别\',
          `social_accounts` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 社交账户 产品说手动补目前保留字段\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `category` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 类别\',
          `actual_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'验证网址\',
          `interflow` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 社交账号\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理  5.异常数据需要人工处理 \',
          `resources_status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已下载  3.处理异常-部分未下载需要人工审核\',
          `resources_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 资源信息\',
          `resources_odd_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 资源异常信息\',
          `source` tinyint(4) DEFAULT \'1\' COMMENT \' 1.演员处理来源  2.影片处理来源【影片处理来源的时候演员处理需要重新更新】 3.异常【这个状态表示数据冲突需要人工处理】  \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_actor_id` (`id`) USING BTREE,
          KEY `id_collection_actor_name` (`name`) USING BTREE,
          KEY `id_collection_actor_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_actor_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集演员信息表\';',

        'CREATE TABLE IF NOT EXISTS `collection_actor_name` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员基础表关联ID 一个演员可能有很多名称\',
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员名称\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_actor_name_id` (`id`) USING BTREE,
          KEY `id_collection_actor_name_aid` (`aid`) USING BTREE,
          KEY `id_collection_actor_name_name` (`name`) USING BTREE,
          KEY `id_collection_actor_name_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集演员名称关联表\';',

        'CREATE TABLE IF NOT EXISTS `collection_series` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'系列名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `category` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 类别\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理  【人工处理】  3.系统处理 4.需要重新处理 5.异常数据需要人工处理\',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_series_id` (`id`) USING BTREE,
          KEY `id_collection_series_name` (`name`) USING BTREE,
          KEY `id_collection_series_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_series_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集系列表\';',

        'CREATE TABLE IF NOT EXISTS `collection_director` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'导演名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理  5.异常数据需要人工处理 \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_director_id` (`id`) USING BTREE,
          KEY `id_collection_director_name` (`name`) USING BTREE,
          KEY `id_collection_director_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_director_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集导演表\';',

        'CREATE TABLE IF NOT EXISTS `collection_label` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'标签名称-主\',
          `name_temp` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'标签名称-临时\',
          `name_child` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'标签名称-子\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理 5.异常数据需要人工处理  \',
          `category` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 类别\',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_label_id` (`id`) USING BTREE,
          KEY `id_collection_label_name` (`name`) USING BTREE,
          KEY `id_collection_label_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_label_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集标签表\';',

        'CREATE TABLE IF NOT EXISTS  `collection_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `type` tinyint(4) DEFAULT \'1\' COMMENT \' 类别类型 1.影片 2.演员 3.标签  4.系列 5.片商\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理  【人工处理】  3.系统处理 4.需要重新处理 5.异常数据需要人工处理 \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_category_id` (`id`) USING BTREE,
          KEY `id_collection_category_name` (`name`) USING BTREE,
          KEY `id_collection_category_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集类别表\';',

        'CREATE TABLE IF NOT EXISTS `collection_movie` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `number` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号\',
          `number_source` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'源番号\',
          `number_name` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号名称\',
          `name` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'影片名称/标题\',
          `source_site` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'来源网站\',
          `source_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'来源路径\',
          `director` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'导演名称\',
          `sell` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'卖家\',
          `time` int(11) unsigned DEFAULT NULL COMMENT \'播放时长/秒\',
          `release_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'发布/发行时间\',
          `small_cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'小封面\',
          `big_cove` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'大封面\',
          `trailer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'预告片\',
          `map` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 其他组图-预览图\',
          `series` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'系列\',
          `film_companies` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'片商\',
          `issued` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'发行\',
          `actor` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 演员\',
          `category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别\',
          `label` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 标签\',
          `score` float unsigned  DEFAULT \'0\' COMMENT \'评分\',
          `score_people` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评分人数\',
          `comment_num` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评论数\',
          `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 评论数组\',
          `actual_source` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'验证网址\',
          `flux_linkage_num` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'磁链信息数\',
          `flux_linkage` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 磁链信息\',
          `is_download` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.不可下载  2.可下载  \',
          `is_subtitle` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.不含字幕  2.含字幕  \',
          `is_new` tinyint(4) DEFAULT \'2\' COMMENT \'状态 1.是今日新种  2.否今日新种 \',
          `abnormal_data_id` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 异常数据ID组\',  
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】 3.系统处理 4.舍弃 5.异常数据需要人工处理\',
          `resources_status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已下载  3.处理异常-部分未下载需要人工审核\',
          `resources_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 资源信息\',
          `resources_odd_info` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 资源异常信息\',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `dis_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理计数防止处理过快导致部分视频附属属性还未处理\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `ctime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'同步爬取时间\',
          `utime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'同步更新时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_movie_id` (`id`) USING BTREE,
          KEY `id_collection_movie_number` (`number`) USING BTREE,
          KEY `id_collection_movie_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_movie_name` (`name`) USING BTREE,
          KEY `id_collection_movie_status` (`status`) USING BTREE,
          KEY `id_collection_movie_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集影片信息表\';',

        'CREATE TABLE IF NOT EXISTS `collection_number` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理  \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_number_id` (`id`) USING BTREE,
          KEY `id_collection_number_name` (`name`) USING BTREE,
          KEY `id_collection_number_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_number_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集番号表\';',

        'CREATE TABLE IF NOT EXISTS `collection_comments` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `user_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'评论的用户名称\',
          `number` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'评论的番号\',
          `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'评论的内容\',
          `score` float DEFAULT \'0\' COMMENT \'评分0代表没有评分\',
          `content_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'评论的时间\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理  5.已放弃 \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_comments_id` (`id`) USING BTREE,
          KEY `id_collection_comments_user_name` (`user_name`) USING BTREE,
          KEY `id_collection_comments_number` (`number`) USING BTREE,
          KEY `id_collection_comments_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_comments_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集评论表\';',

        'CREATE TABLE IF NOT EXISTS `collection_score` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `user_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'评论的用户名称\',
          `number` char(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'评论的番号\',
          `score` float unsigned  DEFAULT \'0\' COMMENT \'评分\',
          `content_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'评分的时间\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.未处理  2.已处理【人工处理】  3.系统处理 4.需要重新处理 5.已放弃 \',
          `admin_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'处理用户id\',
          `original_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_collection_score_id` (`id`) USING BTREE,
          KEY `id_collection_score_user_name` (`user_name`) USING BTREE,
          KEY `id_collection_score_number` (`number`) USING BTREE,
          KEY `id_collection_score_admin_id` (`admin_id`) USING BTREE,
          KEY `id_collection_score_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'采集评分表\';',

        /************************影片部分表**************************/

        'CREATE TABLE IF NOT EXISTS `movie_piece_list` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'创建的用户ID\',
          `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'名称/标题\',
          `cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'封面\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量-冗余\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `pv_browse_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'pv浏览次数\',
          `intro` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'片单简介\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
          `is_hot` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.热门  \',
          `authority` tinyint(4) DEFAULT \'1\' COMMENT \' 1.公开  2.仅自己可见  \',
          `type` tinyint(4) DEFAULT \'1\' COMMENT \' 1.用户创建  2.系统/管理员创建 3.用户默认  \',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_piece_list_id` (`id`) USING BTREE,
          KEY `id_movie_piece_list_uid` (`uid`) USING BTREE,
          KEY `id_movie_piece_list_name` (`name`) USING BTREE,
          KEY `id_movie_piece_list_is_hot` (`is_hot`) USING BTREE,
          KEY `id_movie_piece_list_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片片单表\';',

        'CREATE TABLE IF NOT EXISTS `piece_list_movie` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `plid` bigint(20) unsigned NOT NULL DEFAULT \'0\' COMMENT \'片单ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_piece_list_movie_id` (`id`) USING BTREE,
          KEY `id_piece_list_movie_plid` (`plid`) USING BTREE,
          KEY `id_piece_list_movie_mid` (`mid`) USING BTREE,
          KEY `id_user_piece_list_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'片单影片表\';',

        'CREATE TABLE IF NOT EXISTS  `movie_actor_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_actor_category_id` (`id`) USING BTREE,
          KEY `id_movie_actor_category_name` (`name`) USING BTREE,
          KEY `id_movie_actor_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片演员类别表\';',

        'CREATE TABLE IF NOT EXISTS `movie_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_category_id` (`id`) USING BTREE,
          KEY `id_movie_category_name` (`name`) USING BTREE,
          KEY `id_movie_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片类别表\';',

        'CREATE TABLE IF NOT EXISTS `movie_label_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_label_category_id` (`id`) USING BTREE,
          KEY `id_movie_label_category_name` (`name`) USING BTREE,
          KEY `id_movie_label_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片标签类别表\';',

        'CREATE TABLE IF NOT EXISTS `movie_label` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'父标签ID 0 表示顶级标签\',
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'标签名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_label_id` (`id`) USING BTREE,
          KEY `id_movie_label_cid` (`cid`) USING BTREE,
          KEY `id_movie_label_name` (`name`) USING BTREE,
          KEY `id_movie_label_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片标签表\';',

        'CREATE TABLE IF NOT EXISTS `movie_label_category_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `lid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'标签ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_label_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_label_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_label_category_associate_lid` (`lid`) USING BTREE,
          KEY `id_movie_label_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片标签类别关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_director` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'导演名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量-冗余\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_director_id` (`id`) USING BTREE,
          KEY `id_movie_director_name` (`name`) USING BTREE,
          KEY `id_movie_director_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片导演表\';',

        'CREATE TABLE IF NOT EXISTS `movie_series` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'系列名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量-冗余\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_series_id` (`id`) USING BTREE,
          KEY `id_movie_series_name` (`name`) USING BTREE,
          KEY `id_movie_series_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片系列表\';',

        'CREATE TABLE IF NOT EXISTS `movie_series_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_series_category_id` (`id`) USING BTREE,
          KEY `id_movie_series_category_name` (`name`) USING BTREE,
          KEY `id_movie_series_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片系列类别表\';',

        'CREATE TABLE IF NOT EXISTS `movie_series_category_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `series_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'系列ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_series_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_series_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_series_category_associate_series_id` (`series_id`) USING BTREE,
          KEY `id_movie_series_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片系列类别关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_film_companies` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'片商名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量-冗余\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_film_companies_id` (`id`) USING BTREE,
          KEY `id_movie_film_companies_name` (`name`) USING BTREE,
          KEY `id_movie_film_companies_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片片商表\';',

        'CREATE TABLE IF NOT EXISTS `movie_film_companies_category` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'类别名称\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_film_companies_category_id` (`id`) USING BTREE,
          KEY `id_movie_film_companies_category_name` (`name`) USING BTREE,
          KEY `id_movie_film_companies_category_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片片商类别表\';',

        'CREATE TABLE IF NOT EXISTS `movie_film_companies_category_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `film_companies_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'片商ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_film_companies_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_film_companies_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_film_companies_category_associate_film_companies_id` (`film_companies_id`) USING BTREE,
          KEY `id_movie_film_companies_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片片商类别关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_actor` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员名称\',
          `photo` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员照片\',
          `sex` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员性别\',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `social_accounts` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 社交账户\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量-冗余\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_actor_id` (`id`) USING BTREE,
          KEY `id_movie_actor_name` (`name`) USING BTREE,
          KEY `id_movie_actor_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片演员表\';',

        'CREATE TABLE IF NOT EXISTS `movie_actor_name` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员基础表关联ID 一个演员可能有很多名称\',
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'演员名称\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_actor_name_id` (`id`) USING BTREE,
          KEY `id_movie_actor_name_aid` (`aid`) USING BTREE,
          KEY `id_movie_actor_name_name` (`name`) USING BTREE,
          KEY `id_movie_actor_name_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'演员名称关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_actor_category_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_actor_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_actor_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_actor_category_associate_aid` (`aid`) USING BTREE,
          KEY `id_movie_actor_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片演员类别关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `number` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号\',
          `number_source` char(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'原番号\',
          `name` varchar(750) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'影片名称\',
          `time` int(11) unsigned DEFAULT NULL COMMENT \'播放时长/秒\',
          `release_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'发布/发行时间\',
          `issued` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'发行\',
          `sell` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'卖家\',
          `small_cover` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'小封面\',
          `big_cove` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'大封面\',
          `trailer` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'预告片\',
          `map` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 其他组图-预览图\',
          `score` float unsigned  DEFAULT \'0\' COMMENT \'评分-计算过后的\',
          `score_people` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评分人数-冗余\',
          `comment_num` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评论数\',
          `collection_score` float unsigned NOT NULL DEFAULT \'0\' COMMENT \'评分-采集\',
          `collection_score_people` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评分人数-冗余-采集\',
          `collection_comment_num` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'评论数-采集\',
          `wan_see` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'想看数量-冗余\',
          `seen` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'看过数量-冗余\',
          `flux_linkage_num` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'磁链信息数\',
          `flux_linkage` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'json 数组 磁链信息\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.正常  2.禁用  \',
          `is_download` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.不可下载  2.可下载  \',
          `is_subtitle` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.不含字幕  2.含字幕  \',
          `is_hot` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.普通  2.热门  \',
          `is_short_comment` tinyint(4) DEFAULT \'1\' COMMENT \'状态 1.不含短评  2.含短评  \',
          `is_up` tinyint(4) DEFAULT \'1\' COMMENT \' 1.上架  2.下架  \',
          `new_comment_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'最新评论时间 -冗余\',
          `flux_linkage_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'磁链更新时间\',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          UNIQUE KEY `number` (`number`),
          KEY `id_movie_id` (`id`) USING BTREE,
          KEY `id_movie_number` (`number`) USING BTREE,
          KEY `id_movie_name` (`name`) USING BTREE,
          KEY `id_movie_is_download` (`is_download`) USING BTREE,
          KEY `id_movie_is_subtitle` (`is_subtitle`) USING BTREE,
          KEY `id_movie_created_at` (`created_at`) USING BTREE,
          KEY `id_movie_score` (`score`) USING BTREE,
          KEY `id_movie_collection_score` (`collection_score`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片基础信息表\';',

        'CREATE TABLE IF NOT EXISTS `movie_score_notes` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常计分  2.取消计分  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `score` float unsigned NOT NULL DEFAULT \'0\' COMMENT \'评分\',
          `collection_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'来源采集ID - 只有source_type 为3时生效\',
          `nickname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'模拟 用户昵称 --目前只有采集的才会\',
          `source_type` tinyint(4) DEFAULT \'1\' COMMENT \'来源类型 1.用户评分 2.虚拟用户评分 3.采集评分 \',
          `score_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'评分时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_score_notes_id` (`id`) USING BTREE,
          KEY `id_movie_score_notes_uid` (`uid`) USING BTREE,
          KEY `id_movie_score_notes_mid` (`mid`) USING BTREE,
          KEY `id_movie_score_notes_collection_id` (`collection_id`) USING BTREE,
          KEY `id_movie_score_notes_score_time` (`score_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片评分记录\';',

        'CREATE TABLE IF NOT EXISTS `movie_comment` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID/回复的用户ID\',
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'归属评论ID 0表示顶级评论\',
          `collection_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'来源采集ID - 只有source_type 为3时生效\',
          `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'评论记录\',
          `score` float DEFAULT \'0\' COMMENT \'评分0代表没有评分\',
          `type` tinyint(4) DEFAULT \'1\' COMMENT \'评论类型 1.评论  2.回复  \',
          `source_type` tinyint(4) DEFAULT \'1\' COMMENT \'来源类型 1.用户评论 2.虚拟用户评论 3.采集评论 \',
          `nickname` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT \'模拟 用户昵称 --目前只有采集的才会\',
          `avatar` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'模拟 头像 -- 目前只有采集的才会\',
          `reply_uid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'回复的目标用户ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `like` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'赞\',
          `dislike` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'踩\',
          `comment_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'评论时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_comment_id` (`id`) USING BTREE,
          KEY `id_movie_comment_uid` (`uid`) USING BTREE,
          KEY `id_movie_comment_mid` (`mid`) USING BTREE,
          KEY `id_movie_comment_cid` (`cid`) USING BTREE,
          KEY `id_movie_comment_collection_id` (`collection_id`) USING BTREE,
          KEY `id_movie_comment_type` (`type`) USING BTREE,
          KEY `id_movie_comment_reply_uid` (`reply_uid`) USING BTREE,
          KEY `id_movie_comment_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片评论表\';',


        'CREATE TABLE IF NOT EXISTS `movie_category_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_category_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片类别关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_label_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_category_associate_id` (`id`) USING BTREE,
          KEY `id_movie_category_associate_cid` (`cid`) USING BTREE,
          KEY `id_movie_category_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_category_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片标签关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_actor_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_actor_associate_id` (`id`) USING BTREE,
          KEY `id_movie_actor_associate_aid` (`aid`) USING BTREE,
          KEY `id_movie_actor_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_actor_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片演员关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_director_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `did` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'导演ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_director_associate_id` (`id`) USING BTREE,
          KEY `id_movie_director_associate_did` (`did`) USING BTREE,
          KEY `id_movie_director_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_director_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片导演关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_series_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `series_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'导演ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_series_associate_id` (`id`) USING BTREE,
          KEY `id_movie_series_associate_series_id` (`series_id`) USING BTREE,
          KEY `id_movie_series_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_series_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片系列关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_film_companies_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `film_companies_id` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'导演ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_film_companies_associate_id` (`id`) USING BTREE,
          KEY `id_movie_film_companies_associate_film_companies_id` (`film_companies_id`) USING BTREE,
          KEY `id_movie_film_companies_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_film_companies_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片片商关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_number` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT \'\' COMMENT \'番号名称\',
          `movie_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片数量\',
          `like_sum` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'收藏数量-冗余\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `oid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'源数据ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_number_id` (`id`) USING BTREE,
          KEY `id_movie_number_name` (`name`) USING BTREE,
          KEY `id_movie_number_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片番号表\';',

        'CREATE TABLE IF NOT EXISTS `movie_number_associate` (
          `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
          `nid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'番号ID\',
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.弃用  \',
          `associate_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'关联时间\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_number_associate_id` (`id`) USING BTREE,
          KEY `id_movie_number_associate_nid` (`nid`) USING BTREE,
          KEY `id_movie_number_associate_mid` (`mid`) USING BTREE,
          KEY `id_movie_number_associate_associate_time` (`associate_time`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片番号关联表\';',

        'CREATE TABLE IF NOT EXISTS `movie_log` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `mid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'影片ID\',
          `cid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          PRIMARY KEY (`id`),
          KEY `id_movie_log_id` (`id`) USING BTREE,
          KEY `id_movie_log_mid` (`mid`) USING BTREE,
          KEY `id_movie_log_cid` (`cid`) USING BTREE,
          KEY `id_movie_log_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'影片浏览记录-PV统计使用\';',

        'CREATE TABLE IF NOT EXISTS `actor_log` (
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
          `aid` int(11) unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员ID\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          PRIMARY KEY (`id`),
          KEY `id_actor_log_id` (`id`) USING BTREE,
          KEY `id_actor_log_aid` (`aid`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'演员浏览记录-PV统计使用\';',

        'CREATE TABLE IF NOT EXISTS  `emailorsms_log` (
          `id` bigint(20) NOT NULL AUTO_INCREMENT,
          `emailorphone` varchar(128) DEFAULT NULL COMMENT \'手机或者邮箱号码\',
          `message` text COMMENT \'消息内容\',
          `type` tinyint(1) DEFAULT \'1\' COMMENT \' 数据类型 1.手机 2. 邮箱 \',
          `code` varchar(20) DEFAULT NULL COMMENT \'验证码\',
          `uid` bigint(20) DEFAULT NULL COMMENT \'用户id\',
          `ip` varchar(50) DEFAULT NULL,
          `timestamp` int(11) NOT NULL DEFAULT \'0\' COMMENT \'发送的时间戳\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          PRIMARY KEY (`id`),
          KEY `id_emailorsms_log_emailorphone` (`emailorphone`) USING BTREE,
          KEY `id_emailorsms_log_uid` (`uid`) USING BTREE,
          KEY `id_emailorsms_log_code` (`code`) USING BTREE
        ) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COMMENT=\'验证码业务表\';',

        'CREATE TABLE IF NOT EXISTS `actor_popularity_chart` (
          `id` int unsigned NOT NULL AUTO_INCREMENT,
          `aid` int unsigned NOT NULL DEFAULT \'0\' COMMENT \'演员ID\',
          `cid` int unsigned NOT NULL DEFAULT \'0\' COMMENT \'类别ID\',
          `mtime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'月份\',
          `hot_val` float  NOT NULL DEFAULT \'0\' COMMENT \'热度值\',
          `up_mhot` float  NOT NULL DEFAULT \'0\' COMMENT \'上月热度值\',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_actor_popularity_chart_id` (`id`) USING BTREE,
          KEY `id_actor_popularity_chart_aid` (`aid`) USING BTREE,
          KEY `id_actor_popularity_chart_hot_val` (`hot_val`) USING BTREE,
          KEY `id_actor_popularity_chart_mtime` (`mtime`) USING BTREE,
          KEY `id_actor_popularity_chart_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'演员热度值表\';',

        'CREATE TABLE IF NOT EXISTS `user_search_log` (
          `id` int unsigned NOT NULL AUTO_INCREMENT,
          `uid` int unsigned NOT NULL DEFAULT \'0\' COMMENT \'用户ID\',
          `content` varchar(255) DEFAULT NULL COMMENT \'搜索内容\',
          `status` tinyint(4) DEFAULT \'1\' COMMENT \' 1.正常  2.删除  \',
          `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT \'创建时间\',
          `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT \'更新时间\',
          PRIMARY KEY (`id`),
          KEY `id_user_search_log_id` (`id`) USING BTREE,
          KEY `id_user_search_log_aid` (`uid`) USING BTREE,
          KEY `id_user_search_log_created_at` (`created_at`) USING BTREE
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT=\'用户搜索记录\';',




    ];
}